---
output: 
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    fig_caption: TRUE
    latex_engine: xelatex
    number_sections: TRUE
    toc: FALSE
    toc_depth: 3
    keep_tex: TRUE
documentclass: book
lot: FALSE
lof: FALSE
fontsize: 12pt
indent: true
bibliography: library.bib
csl: ama-citation.csl
---


```{r setup6, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
require(knitr); require(kableExtra); require(bookdown); require(tidyverse)
devtools::load_all("C:/Users/ajstamm/Documents/GitHub/Coding/apcmpkg/R")
```

<!-- ## References {-}  -->
<!-- from aim 1 --->

<!-- \pagebreak -->

<!-- https://tex.stackexchange.com/questions/85776/change-figure-numbering-for-appendix -->


# (APPENDIX) Appendix {-}

<!-- \counterwithin{table}{section} -->
<!-- \setcounter{table}{0} -->

# Supplemental Tables for Chapter 3

\renewcommand{\thetable}{A.\arabic{table}}

\blandscape

```{r rrcum2all, echo=FALSE, message = FALSE}
t <- readxl::read_xls("data/model2rr_tables.xls", sheet = "cumulative") %>%
  mutate(air = gsub("2.5$", "\textsubscript{2.5}", air),
         air = gsub("\\\\\\\\", "\\\\", air),
         green = gsub("_", "-", green),
         pollutant = paste(air, measure)) %>%
  select(bd, pollutant, green, lags, b_50, b_100, b_200, b_300, b_400, b_500)

t %>% select(-bd) %>% 
  kable(booktabs = TRUE, format = "latex", longtable = T, escape = F, # 
        caption = "Cumulative risk ratios for covariate models of air pollutant and birth defects pairs with green space, New York State outside New York City, 2002 to 2015", 
        col.names = c("Pollutant", "Green space", "Weeks", "50m buffer", "100m buffer", 
                      "200m buffer", "300m buffer", "400m buffer", "500m buffer"), 
        align = c(rep("l", 2), rep("c", 7))) %>%
  row_spec(0, bold=TRUE) %>%
  column_spec(1, bold = FALSE, width = "6em") %>% # 
  column_spec(2, bold = FALSE, width = "5em") %>% # 
  column_spec(3, bold = FALSE, width = "2em") %>% # 
  column_spec(4:9, bold = FALSE, width = "7em") %>% # 
  kableExtra::group_rows(group_label = "Clubfoot", start_row = 1, 
                         end_row = 8) %>%
  kableExtra::group_rows(group_label = "Cleft lip with or without cleft palate", 
                         start_row = 9, end_row = 24) %>%
  kableExtra::group_rows(group_label = "Cleft palate", start_row = 25, 
                         end_row = 40) %>%
  kableExtra::group_rows(group_label = "Craniosynostosis", start_row = 41, 
                         end_row = 56) %>%
  kableExtra::collapse_rows(1:2, latex_hline = "major", valign = "top") %>%
  # column_spec(5:6, bold = FALSE, width = "8em") %>% # 
  kableExtra::kable_styling(
    latex_options = c("repeat_header"), # "hold_position", "striped", 
    font_size = 9.5, # full_width = TRUE, position = "center", 
    repeat_header_continued = "\\textit{(Continued on Next Page...)}") %>% 
    footnote(c("NA = Data not applicable, either model not run or weeks not included.",
"Model was adjusted for maternal education level, maternal smoking, tract-level median income, conception season, and the indicated green space variable. ", 
               "For green space, grass-trees is a composite variable of grasses and trees and green-water is a composite of grasses, trees, and water.",
               "For the initial analysis, clubfoot was not run for the 12-week model."))

```

\clearpage

```{r rrcf16g, echo=FALSE, message = FALSE}
bd_rr2_tables(my_sheet = "cf_16", bold_rows = c(0, 43:46, 53:57, 64, 70, 78),
              my_caption = "Risk ratios for covariate clubfoot 16-week models of air pollutant and birth defects pairs with green space, New York State outside New York City, 2002 to 2015")

```

\clearpage

```{r rrclp12g, echo=FALSE, message = FALSE}
bd_rr2_tables(my_sheet = "clp_12", bold_rows = c(0, 10, 13, 23, 26, 40, 43, 53, 56),
              my_caption = "Risk ratios for covariate cleft lip with or without cleft palate 12-week models of air pollutant and birth defects pairs with green space, New York State outside New York City, 2002 to 2015")

```

\clearpage

```{r rrclp16g, echo=FALSE}
bd_rr2_tables(my_sheet = "clp_16", bold_rows = c(0, 19:22, 27:30, 32:33, 36:39, 44:47, 49:50),
              my_caption = "Risk ratios for covariate cleft lip with or without cleft palate 16-week models of air pollutant and birth defects pairs with green space, New York State outside New York City, 2002 to 2015")

```

\clearpage

```{r rrcp12g, echo=FALSE, message = FALSE}
bd_rr2_tables(my_sheet = "cp_12", bold_rows = c(0, 13:17, 59:61),
              my_caption = "Risk ratios for covariate cleft palate 12-week models of air pollutant and birth defects pairs with green space, New York State outside New York City, 2002 to 2015")

```

\clearpage

```{r rrcp16g, echo=FALSE, message = FALSE}
bd_rr2_tables(my_sheet = "cp_16", bold_rows = c(0),
              my_caption = "Risk ratios for covariate cleft palate 16-week models of air pollutant and birth defects pairs with green space, New York State outside New York City, 2002 to 2015")

```

\clearpage

```{r rrcs12g, echo=FALSE, message = FALSE}
bd_rr2_tables(my_sheet = "cs_12", bold_rows = c(0, 2:3, 6, 9:10, 13, 24, 27, 33, 36, 49:50, 61:62),
              my_caption = "Risk ratios for covariate craniosynostosis 12-week models of air pollutant and birth defects pairs with green space, New York State outside New York City, 2002 to 2015")

```

\clearpage

```{r rrcs16g, echo=FALSE, message = FALSE}
bd_rr2_tables(my_sheet = "cs_16", bold_rows = c(0, 6:8, 12, 14:16, 29:31, 46:48, 
                                                51, 55:56, 61, 65:66, 70),
              my_caption = "Risk ratios for covariate craniosynostosis 16-week models of air pollutant and birth defects pairs with green space, New York State outside New York City, 2002 to 2015")

```

\elandscape

# Supplemental Tables for Chapter 4

\renewcommand{\thetable}{B.\arabic{table}}




```{r rrcum3, echo=FALSE, message = FALSE, eval=TRUE}
  my_foot <- c(
    "NA = Data not applicable, either model not run or weeks not included.",
    paste("Model was adjusted for O\\\\textsubscript{3},",
                     "PM\\\\textsubscript{2.5}, maternal education level,",
                     "maternal smoking, "),
               paste("tract-level median income, conception season,",
                     "and presence of grasses or trees."),
               "Values in bold were significant at $\\\\alpha = 0.05$.")

t <- readr::read_csv("data/model3cov_rrciwide_2022-08-26_all.csv") |>
  filter(lag == "cum", model_type == "adjusted") |> 
  mutate(model = gsub("_1._b.+", "", model), 
         o3 = ifelse(is.na(o3), "", o3),
         pm = ifelse(is.na(pm), "", pm),
         buffer = as.numeric(gsub("b", "", buffer)),
         buffer = factor(buffer, labels = paste0(c(50, seq(100, 500, by = 100)), "m"))) |>
  select(lags, model, buffer, o3, pm) |>
  arrange(model, buffer)

t16 <- t |> dplyr::filter(lags == 16)
t12 <- t |> dplyr::filter(lags == 12)

t <- dplyr::full_join(t16, t12, by = c("model", "buffer")) |>
  dplyr::mutate(o3.x = ifelse(is.na(o3.x), "", o3.x),
                pm.x = ifelse(is.na(pm.x), "", pm.x),
                o3.y = ifelse(is.na(o3.y), "", o3.y),
                pm.y = ifelse(is.na(pm.y), "", pm.y))

b <- table(t$model)

lbl <- paste(c(rep("Clubfoot", 2), rep("Cleft lip with or without cleft palate", 2), 
               rep("Cleft palate", 2), rep("Craniosynostosis", 2)), "case group, weekly", 
             rep(c("mean", "peak"), 4), "concentration")

names(b) <- lbl

t |> select(-model, -starts_with("lags")) |> 
  kable(booktabs = TRUE, format = "latex", longtable = T, escape = F, # 
        caption = "Cumulative risk ratios for covariate models of mixed air pollutants and birth defects, New York State outside New York City, 2002 to 2015", 
        col.names = c("Buffer", rep(c("O\\textsubscript{3}", "PM\\textsubscript{2.5}"), 2)), 
        align = c("l", rep("c", 4))) |>
  kableExtra::group_rows(index = b, escape = F) |> # 
  add_header_above(c(" ", "16 week model" = 2, "12 week model" = 2)) |>
  row_spec(0, bold=TRUE) |>
  kableExtra::row_spec(cumsum(b), hline_after = TRUE) |>
  column_spec(1, bold = FALSE, width = "4em") |> # 
  column_spec(2:5, bold = FALSE, width = "8em") |> # 
  # column_spec(5:6, bold = FALSE, width = "8em") |> # 
  kableExtra::kable_styling(
    latex_options = c("repeat_header", "striped"), # "hold_position", 
    font_size = 11, # full_width = TRUE, position = "center", 
    repeat_header_continued = "\\textit{(Continued on Next Page...)}") |> 
    footnote(my_foot, escape = F)

```

\pagebreak

```{r rrcf3, echo=FALSE, message = FALSE}
bd_rr3_tables(my_bd = "cf", 
              my_caption = "Risk ratios for covariate clubfoot mixed air pollutant models, New York State outside New York City, 2002 to 2015")

```

\pagebreak

```{r rrclp3, echo=FALSE, message = FALSE}
bd_rr3_tables(my_bd = "clp", 
              my_caption = "Risk ratios for covariate cleft lip with or without cleft palate mixed air pollutant models, New York State outside New York City, 2002 to 2015")

```

\pagebreak

```{r rrcp3, echo=FALSE, message = FALSE}
bd_rr3_tables(my_bd = "cp", 
              my_caption = "Risk ratios for covariate cleft palate mixed air pollutant models, New York State outside New York City, 2002 to 2015")

```

\pagebreak

```{r rrcs3, echo=FALSE, message = FALSE}
bd_rr3_tables(my_bd = "cs", 
              my_caption = "Risk ratios for covariate craniosynostosis mixed air pollutant models, New York State outside New York City, 2002 to 2015")

```

